### ISSUE TITLE
Automate posting upcoming GTFS to future-service branch

### ISSUE THREAD

**Issue by matikin9** [LACMTA/gtfs-bus#2]
Goal: Friday, 12/2/22

- [ ] Provide Rollin with a process to kick off the automation when the new GTFS is ready:
  - [x] LACMTA/lacmta-gtfs#13
  - [ ] LACMTA/gtfs_bus#4
- [ ] LACMTA/gtfs_bus#3
- [ ] #6
